default: &default
  adapter: postgis
  encoding: unicode
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: vedoc-api_test

production:
  <<: *default